### ISSUE TITLE
A list with all available fields for products

### ISSUE THREAD

**Issue by InFog** [productsupcom/Platform-API-Client#1]
Hi!

I think you could add a list with all available fields for products in the examples.
A small description along with the field name would be great :)

Thanks

**Comment by 0bp** [comment]
Hey,

we don't limit the fields for products so you can use whatever you want but best practice is to adapt the google merchant center / adwords format.

https://support.google.com/merchants/answer/188494?hl=de

- Boris

**Comment by InFog** [comment]
Thank you, @0bp :)
