### ISSUE TITLE
ID check with product insertion

### ISSUE THREAD

**Issue by hokkaido** [productsupcom/Platform-API-Client#6]
if(!array_key_exists('id',$row)) {
      throw new Exceptions\ClientException('adding one column "id" to the product data is mandatory');
    }

Why is this mandatory? In productsup, one can define their own unique product identifiers, so this is counter intuitive. 

Do you actually do a duplicate check on an id field during import? I'm having the issue that with products that have the same value with their id field (unique identifier is actually a different field, long story), only one of them gets imported (the last one).

**Comment by Nik-Int** [comment]
Yes the id attribute needs to be unique to identify products through the API. E.g. to update one specific product or to delete it. With duplicates there would issues which specific product would be updated or deleted.
Uploading regular CSV feeds with FTP does not run into this issue as data does not need to be addressable on product level. For this case the unique ID can be created (with ID column setting or unique ID service) on the platform but specific products not updated through the API
